# Cerchiamo di studiare meglio le persone passate 5 anni

In [2]:
import pandas as pd
import numpy as np

In [3]:
Cese = pd.read_pickle("data/da_usare/Cese_2003-2024_data.pickle")
Cese

,anno,studente,posizione,regione,classe,es1,es2,es3,es4,es5,es6,tot,medaglia,anno_breve,pt123,pt456,zona,colore
0,2003,Tiozzo Giulio,1,Piemonte,5,7,7,7,6,7,7,41,ORO,03,21,20,Nord-Ovest,Gold
1,2003,Mantova Vincenzo,2,Lombardia,5,7,7,7,7,7,5,40,ORO,03,21,19,Nord-Ovest,Gold
2,2003,Barbieri Luca,3,Lombardia,3,7,7,7,4,4,7,36,ORO,03,21,15,Nord-Ovest,Gold
3,2003,D'Aurizio Jacopo,3,Abruzzo,5,7,2,7,6,7,7,36,ORO,03,16,20,Sud,Gold
4,2003,Ghiraldin Francesco,3,Veneto,5,7,7,7,7,7,1,36,ORO,03,21,15,Nord-Est,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6579,2024,Saggiorato Leonardo,292,-,-1,0,3,0,0,0,0,3,-,24,3,0,-,#7FFF00
6580,2024,Miccichè Calogero,293,-,-1,0,2,0,0,0,0,2,-,24,2,0,-,#7FFF00
6581,2024,Celebre Francesco,293,-,-1,0,0,2,0,0,0,2,-,24,2,0,-,#7FFF00
6582,2024,La Malfa Salvatore,295,-,-1,0,0,0,0,0,0,0,-,24,0,0,-,#7FFF00
6583,2024,Garritano Giovanni,295,-,-1,0,0,0,0,0,0,0,-,24,0,0,-,#7FFF00

In [4]:
a = Cese.groupby("studente").size().sort_values(ascending=False)
a = a[a == 5]
a

studente
Re Giuseppe             5
Migliorini Matteo       5
Balistri Edoardo        5
Bulst Leander           5
Stra Federico           5
Tafuri Paolo            5
Baccioli Avio           5
Morgante Matteo         5
Tarini Bernardo         5
Calogero Giacomo        5
Toffanin Damiano        5
Lattaruolo Gianmarco    5
Lavacca Simone          5
Trevisiol Marco         5
Barakat Youness         5
Ulliana Andrea          5
Antonucci Clara         5
Antonelli Gioacchino    5
Marzenta Giovanni       5
Deniskin Nikita         5
D'addezio Marco         5
Marino Domenico         5
Lin Francesco           5
Marengon Marco          5
Viola Federico          5
Stancanelli Valerio     5
Barbarino Giovanni      5
Lo Bianco Federico      5
Foschi Massimiliano     5
Raucci Salvatore        5
Pruneri Fabio           5
Protopapa Matteo        5
Colombo Giulio          5
Presel Francesco        5
Bertoli Michele         5
Risari Leonardo         5
Ghidelli Luca           5
Conti Andrea            5
Bolzonella Stefano      5
Pierro Lorenzo          5
Bartoli Davide          5
Sala Francesco          5
Bongiorno Alessio       5
Fogari Andrea           5
Bordigoni Fabio         5
Fiorindo Alessandro     5
Bedin Alberto           5
Beccaccia Alice         5
Corso Gabriele          5
Glaudo Federico         5
Botticella Raffaele     5
Maraviglia Nicola       5
Straffelini Cesare      5
Vizzari Giacomo         5
Lugli Francesco         5
Zeffiro Damiano         5
Zonta Enrico            5
De Pietri Daniele       5
Danesi Davide           5
dtype: int64

In [5]:
Cese[Cese["studente"]=="Bertolini Marco"]

,anno,studente,posizione,regione,classe,es1,es2,es3,es4,es5,es6,tot,medaglia,anno_breve,pt123,pt456,zona,colore
4257,2017,Bertolini Marco,47,Lombardia,2,7,0,5,3,0,0,15,ARGENTO,17,12,3,Nord-Ovest,Silver
4309,2017,Bertolini Marco,106,Lombardia,3,7,0,5,0,0,0,12,BRONZO,17,12,0,Nord-Ovest,#CD7F32
4523,2018,Bertolini Marco,19,Lombardia,4,7,7,4,7,2,1,28,ORO,18,18,10,Nord-Ovest,Gold
4649,2018,Bertolini Marco,139,Lombardia,3,5,7,2,0,0,1,15,BRONZO,18,14,1,Nord-Ovest,#CD7F32
4811,2019,Bertolini Marco,7,Lombardia,5,7,7,7,7,0,2,30,ORO,19,21,9,Nord-Ovest,Gold
4836,2019,Bertolini Marco,31,Lombardia,4,7,5,7,0,1,0,20,ARGENTO,19,19,1,Nord-Ovest,Silver
5176,2020,Bertolini Marco,70,-,-1,7,7,5,1,1,0,21,ARGENTO,20,19,2,-,Silver

In [6]:
Cese[Cese["studente"]=="Re Giuseppe"]

,anno,studente,posizione,regione,classe,es1,es2,es3,es4,es5,es6,tot,medaglia,anno_breve,pt123,pt456,zona,colore
1973,2009,Re Giuseppe,183,Lazio,1,7,0,6,0,0,0,13,MENZIONE,09,13,0,Centro,#FC0FC0
2266,2010,Re Giuseppe,168,Lazio,2,3,1,2,0,0,0,6,-,10,6,0,Centro,#7FFF00
2411,2011,Re Giuseppe,23,Lazio,3,7,7,5,1,2,0,22,ARGENTO,11,19,3,Centro,Silver
2745,2012,Re Giuseppe,50,Lazio,4,7,7,7,7,0,0,28,ARGENTO,12,21,7,Centro,Silver
3004,2013,Re Giuseppe,11,Lazio,5,7,7,6,6,7,0,33,ORO,13,20,13,Centro,Gold

In [7]:
def verifica_autenticita(x):
    vista = Cese[Cese["studente"]==x]
    vista_anno = vista["anno"].reset_index(drop=True)
    bool01 = vista_anno[1] == vista_anno[0] + 1
    bool12 = vista_anno[2] == vista_anno[1] + 1
    bool23 = vista_anno[3] == vista_anno[2] + 1
    bool34 = vista_anno[4] == vista_anno[3] + 1
    return bool01 & bool12 & bool23 & bool34

In [8]:
verifica_autenticita("Bertoli Michele")

True

In [9]:
a.index

Index(['Re Giuseppe', 'Migliorini Matteo', 'Balistri Edoardo', 'Bulst Leander',
       'Stra Federico', 'Tafuri Paolo', 'Baccioli Avio', 'Morgante Matteo',
       'Tarini Bernardo', 'Calogero Giacomo', 'Toffanin Damiano',
       'Lattaruolo Gianmarco', 'Lavacca Simone', 'Trevisiol Marco',
       'Barakat Youness', 'Ulliana Andrea', 'Antonucci Clara',
       'Antonelli Gioacchino', 'Marzenta Giovanni', 'Deniskin Nikita',
       'D'addezio Marco', 'Marino Domenico', 'Lin Francesco', 'Marengon Marco',
       'Viola Federico', 'Stancanelli Valerio', 'Barbarino Giovanni',
       'Lo Bianco Federico', 'Foschi Massimiliano', 'Raucci Salvatore',
       'Pruneri Fabio', 'Protopapa Matteo', 'Colombo Giulio',
       'Presel Francesco', 'Bertoli Michele', 'Risari Leonardo',
       'Ghidelli Luca', 'Conti Andrea', 'Bolzonella Stefano', 'Pierro Lorenzo',
       'Bartoli Davide', 'Sala Francesco', 'Bongiorno Alessio',
       'Fogari Andrea', 'Bordigoni Fabio', 'Fiorindo Alessandro',
       'Bedin Alberto', 'Beccaccia Alice', 'Corso Gabriele', 'Glaudo Federico',
       'Botticella Raffaele', 'Maraviglia Nicola', 'Straffelini Cesare',
       'Vizzari Giacomo', 'Lugli Francesco', 'Zeffiro Damiano', 'Zonta Enrico',
       'De Pietri Daniele', 'Danesi Davide'],
      dtype='object', name='studente')

In [10]:
for x in a.index:
    if not verifica_autenticita(x):
        print(x, "non è passato davvero 5 volte")

Migliorini Matteo non è passato davvero 5 volte

In [11]:
Cese[Cese["studente"]=="Migliorini Matteo"]

,anno,studente,posizione,regione,classe,es1,es2,es3,es4,es5,es6,tot,medaglia,anno_breve,pt123,pt456,zona,colore
462,2004,Migliorini Matteo,154,Lombardia,2,4,0,0,5,0,0,9,-,04,4,5,Nord-Ovest,#7FFF00
1345,2007,Migliorini Matteo,163,Lombardia,5,7,2,0,3,0,0,12,MENZIONE,07,9,3,Nord-Ovest,#FC0FC0
2726,2012,Migliorini Matteo,38,Piemonte,3,7,7,7,7,0,2,30,ARGENTO,12,21,9,Nord-Ovest,Silver
3038,2013,Migliorini Matteo,42,Piemonte,4,6,0,7,7,0,1,21,ARGENTO,13,13,8,Nord-Ovest,Silver
3303,2014,Migliorini Matteo,2,Piemonte,5,7,7,7,7,7,5,40,ORO,14,21,19,Nord-Ovest,Gold

In [12]:
a = a.drop("Migliorini Matteo")
a

studente
Re Giuseppe             5
Balistri Edoardo        5
Bulst Leander           5
Stra Federico           5
Tafuri Paolo            5
Baccioli Avio           5
Morgante Matteo         5
Tarini Bernardo         5
Calogero Giacomo        5
Toffanin Damiano        5
Lattaruolo Gianmarco    5
Lavacca Simone          5
Trevisiol Marco         5
Barakat Youness         5
Ulliana Andrea          5
Antonucci Clara         5
Antonelli Gioacchino    5
Marzenta Giovanni       5
Deniskin Nikita         5
D'addezio Marco         5
Marino Domenico         5
Lin Francesco           5
Marengon Marco          5
Viola Federico          5
Stancanelli Valerio     5
Barbarino Giovanni      5
Lo Bianco Federico      5
Foschi Massimiliano     5
Raucci Salvatore        5
Pruneri Fabio           5
Protopapa Matteo        5
Colombo Giulio          5
Presel Francesco        5
Bertoli Michele         5
Risari Leonardo         5
Ghidelli Luca           5
Conti Andrea            5
Bolzonella Stefano      5
Pierro Lorenzo          5
Bartoli Davide          5
Sala Francesco          5
Bongiorno Alessio       5
Fogari Andrea           5
Bordigoni Fabio         5
Fiorindo Alessandro     5
Bedin Alberto           5
Beccaccia Alice         5
Corso Gabriele          5
Glaudo Federico         5
Botticella Raffaele     5
Maraviglia Nicola       5
Straffelini Cesare      5
Vizzari Giacomo         5
Lugli Francesco         5
Zeffiro Damiano         5
Zonta Enrico            5
De Pietri Daniele       5
Danesi Davide           5
dtype: int64

In [16]:
df = pd.DataFrame(columns=["studente", "anno_finale",
                           "pos1", "pos2", "pos3", "pos4", "pos5",
                           "pt1", "pt2", "pt3", "pt4", "pt5",
                           "menzione", "bronzo", "argento", "oro", "medaglie"])
df

Empty DataFrame
Columns: [studente, anno_finale, pos1, pos2, pos3, pos4, pos5, pt1, pt2, pt3, pt4, pt5, menzione, bronzo, argento, oro, medaglie]
Index: []

In [14]:
len(a)

58

In [15]:
a.index[3]

'Stra Federico'

In [17]:
for i in range( len(a) ):
    nome = a.index[i]
    vista = Cese[ Cese["studente"] == nome ].reset_index(drop=True)
    
    df.at[i, "studente"] = nome
    df.at[i, "anno_finale"] = vista.at[4, "anno"]
    
    df.at[i, "pos1"] = vista.at[0, "posizione"]
    df.at[i, "pos2"] = vista.at[1, "posizione"]
    df.at[i, "pos3"] = vista.at[2, "posizione"]
    df.at[i, "pos4"] = vista.at[3, "posizione"]
    df.at[i, "pos5"] = vista.at[4, "posizione"]
    
    df.at[i, "pt1"] = vista.at[0, "tot"]
    df.at[i, "pt2"] = vista.at[1, "tot"]
    df.at[i, "pt3"] = vista.at[2, "tot"]
    df.at[i, "pt4"] = vista.at[3, "tot"]
    df.at[i, "pt5"] = vista.at[4, "tot"]

    menzione = 0
    bronzo = 0
    argento = 0
    oro = 0
    for j in range(5):
        if vista.at[j, "medaglia"] == "MENZIONE":
            menzione += 1
        elif vista.at[j, "medaglia"] == "BRONZO":
            bronzo += 1
        elif vista.at[j, "medaglia"] == "ARGENTO":
            argento += 1
        elif vista.at[j, "medaglia"] == "ORO":
            oro += 1
    df.at[i, "menzione"] = menzione
    df.at[i, "bronzo"] = bronzo
    df.at[i, "argento"] = argento
    df.at[i, "oro"] = oro
    df.at[i, "medaglie"] = bronzo + argento + oro

df

,studente,anno_finale,pos1,pos2,pos3,pos4,pos5,pt1,pt2,pt3,pt4,pt5,menzione,bronzo,argento,oro,medaglie
0,Re Giuseppe,2013,183,168,23,50,11,13,6,22,28,33,1,0,2,1,3
1,Balistri Edoardo,2024,205,121,12,4,4,8,15,29,36,36,0,1,0,3,4
2,Bulst Leander,2007,232,52,156,102,196,6,16,15,16,10,2,1,1,0,2
3,Stra Federico,2009,58,64,35,28,34,22,19,23,18,26,0,0,5,0,5
4,Tafuri Paolo,2022,263,60,91,13,27,3,16,18,25,26,0,1,2,1,4
5,Baccioli Avio,2022,81,49,126,41,82,19,17,15,22,20,0,3,2,0,5
6,Morgante Matteo,2021,135,250,105,77,66,11,5,14,20,19,0,3,1,0,4
7,Tarini Bernardo,2019,47,7,4,3,9,24,33,35,37,29,0,0,1,4,5
8,Calogero Giacomo,2022,114,49,34,26,27,17,17,25,23,26,0,1,4,0,5
9,Toffanin Damiano,2010,149,151,107,101,98,12,13,9,19,10,1,3,0,0,3
10,Lattaruolo Gianmarco,2018,176,151,87,11,43,9,15,17,27,23,2,1,1,1,3
11,Lavacca Simone,2009,258,168,107,133,77,7,11,16,7,21,2,2,0,0,2
12,Trevisiol Marco,2013,156,16,17,9,11,15,19,23,37,33,1,0,0,4,4
13,Barakat Youness,2014,274,133,144,42,45,1,11,20,21,19,1,1,2,0,3
14,Ulliana Andrea,2017,269,122,9,1,3,1,12,29,37,36,0,1,0,3,4
15,Antonucci Clara,2014,245,32,15,24,9,3,20,35,27,28,0,0,1,3,4
16,Antonelli Gioacchino,2013,123,16,23,1,9,17,19,22,42,34,0,1,1,3,5
17,Marzenta Giovanni,2020,212,106,21,13,17,7,12,26,25,31,0,1,0,3,4
18,Deniskin Nikita,2017,142,13,6,12,4,10,27,30,30,35,1,0,0,4,4
19,D'addezio Marco,2011,242,52,89,168,62,5,14,20,6,16,0,1,2,0,3
20,Marino Domenico,2019,176,132,23,43,31,14,14,20,23,20,1,1,2,1,4
21,Lin Francesco,2007,179,99,32,20,19,10,12,26,25,25,1,1,2,1,4
22,Marengon Marco,2008,72,69,92,19,20,14,21,17,25,23,0,3,0,2,5
23,Viola Federico,2018,176,17,1,2,2,9,28,37,39,39,1,0,0,4,4
24,Stancanelli Valerio,2022,43,15,12,10,5,23,23,33,26,35,0,0,1,4,5
25,Barbarino Giovanni,2011,196,56,14,31,2,10,13,30,15,30,0,0,2,2,4
26,Lo Bianco Federico,2008,99,21,27,8,5,12,28,24,28,35,0,1,1,3,5
27,Foschi Massimiliano,2022,13,1,1,1,1,30,39,42,42,42,0,0,0,5,5
28,Raucci Salvatore,2015,184,275,142,109,31,7,12,10,13,26,1,1,1,0,2
29,Pruneri Fabio,2018,134,41,5,7,7,11,25,34,31,32,0,1,1,3,5
30,Protopapa Matteo,2018,234,151,53,28,282,5,15,22,18,1,1,0,2,0,2
31,Colombo Giulio,2013,201,130,133,38,55,11,8,11,30,19,0,2,2,0,4
32,Presel Francesco,2009,133,127,56,118,54,16,14,21,8,23,1,2,2,0,4
33,Bertoli Michele,2023,241,84,57,103,159,3,19,20,18,12,0,2,1,0,3
34,Risari Leonardo,2023,293,101,151,167,126,0,17,13,13,14,1,2,0,0,2
35,Ghidelli Luca,2010,187,56,11,1,1,10,21,30,42,36,1,0,1,3,4
36,Conti Andrea,2008,33,105,13,7,1,19,18,27,34,37,0,1,1,3,5
37,Bolzonella Stefano,2007,191,52,58,56,27,9,16,22,20,24,0,0,4,0,4
38,Pierro Lorenzo,2019,198,189,160,21,22,13,9,10,26,22,1,0,0,2,2
39,Bartoli Davide,2022,263,241,230,13,12,3,3,6,25,29,0,0,0,2,2
40,Sala Francesco,2015,114,15,9,27,3,13,35,34,23,34,0,1,1,3,5
41,Bongiorno Alessio,2008,111,69,149,151,133,11,21,12,13,7,1,2,0,0,2
42,Fogari Andrea,2010,9,2,1,3,28,28,39,37,39,16,0,0,1,4,5
43,Bordigoni Fabio,2021,86,67,105,43,10,13,20,14,24,26,0,2,2,1,5
44,Fiorindo Alessandro,2014,149,124,32,19,13,7,12,31,28,27,0,1,1,2,4
45,Bedin Alberto,2008,250,186,64,66,68,5,13,19,20,12,0,2,1,0,3
46,Beccaccia Alice,2007,191,62,87,76,66,9,15,20,18,20,0,2,2,0,4
47,Corso Gabriele,2018,253,198,33,16,34,4,13,24,21,24,1,0,2,1,3
48,Glaudo Federico,2013,101,10,4,1,1,19,22,29,42,42,0,1,0,4,5
49,Botticella Raffaele,2024,218,121,18,7,3,7,15,28,33,37,1,1,0,3,4
50,Maraviglia Nicola,2009,249,187,151,205,34,8,10,13,3,26,3,0,1,0,1
51,Straffelini Cesare,2018,265,151,70,8,26,3,15,19,30,25,1,0,2,1,3
52,Vizzari Giacomo,2018,156,111,170,65,10,10,17,10,14,31,1,1,1,1,3
53,Lugli Francesco,2023,241,205,151,62,36,3,8,13,22,25,1,0,2,0,2
54,Zeffiro Damiano,2013,210,77,5,11,14,10,11,28,36,31,0,1,0,3,4
55,Zonta Enrico,2024,245,66,7,2,1,4,19,32,38,42,0,0,1,3,4
56,De Pietri Daniele,2023,83,60,7,34,12,15,22,28,25,32,0,1,2,2,5
57,Danesi Davide,2015,133,78,24,33,17,11,25,27,21,28,0,2,1,2,5

In [18]:
df = df.sort_values("anno_finale", ascending=True)
df

,studente,anno_finale,pos1,pos2,pos3,pos4,pos5,pt1,pt2,pt3,pt4,pt5,menzione,bronzo,argento,oro,medaglie
37,Bolzonella Stefano,2007,191,52,58,56,27,9,16,22,20,24,0,0,4,0,4
2,Bulst Leander,2007,232,52,156,102,196,6,16,15,16,10,2,1,1,0,2
46,Beccaccia Alice,2007,191,62,87,76,66,9,15,20,18,20,0,2,2,0,4
21,Lin Francesco,2007,179,99,32,20,19,10,12,26,25,25,1,1,2,1,4
36,Conti Andrea,2008,33,105,13,7,1,19,18,27,34,37,0,1,1,3,5
45,Bedin Alberto,2008,250,186,64,66,68,5,13,19,20,12,0,2,1,0,3
41,Bongiorno Alessio,2008,111,69,149,151,133,11,21,12,13,7,1,2,0,0,2
26,Lo Bianco Federico,2008,99,21,27,8,5,12,28,24,28,35,0,1,1,3,5
22,Marengon Marco,2008,72,69,92,19,20,14,21,17,25,23,0,3,0,2,5
3,Stra Federico,2009,58,64,35,28,34,22,19,23,18,26,0,0,5,0,5
50,Maraviglia Nicola,2009,249,187,151,205,34,8,10,13,3,26,3,0,1,0,1
32,Presel Francesco,2009,133,127,56,118,54,16,14,21,8,23,1,2,2,0,4
11,Lavacca Simone,2009,258,168,107,133,77,7,11,16,7,21,2,2,0,0,2
9,Toffanin Damiano,2010,149,151,107,101,98,12,13,9,19,10,1,3,0,0,3
35,Ghidelli Luca,2010,187,56,11,1,1,10,21,30,42,36,1,0,1,3,4
42,Fogari Andrea,2010,9,2,1,3,28,28,39,37,39,16,0,0,1,4,5
19,D'addezio Marco,2011,242,52,89,168,62,5,14,20,6,16,0,1,2,0,3
25,Barbarino Giovanni,2011,196,56,14,31,2,10,13,30,15,30,0,0,2,2,4
0,Re Giuseppe,2013,183,168,23,50,11,13,6,22,28,33,1,0,2,1,3
31,Colombo Giulio,2013,201,130,133,38,55,11,8,11,30,19,0,2,2,0,4
16,Antonelli Gioacchino,2013,123,16,23,1,9,17,19,22,42,34,0,1,1,3,5
12,Trevisiol Marco,2013,156,16,17,9,11,15,19,23,37,33,1,0,0,4,4
48,Glaudo Federico,2013,101,10,4,1,1,19,22,29,42,42,0,1,0,4,5
54,Zeffiro Damiano,2013,210,77,5,11,14,10,11,28,36,31,0,1,0,3,4
15,Antonucci Clara,2014,245,32,15,24,9,3,20,35,27,28,0,0,1,3,4
44,Fiorindo Alessandro,2014,149,124,32,19,13,7,12,31,28,27,0,1,1,2,4
13,Barakat Youness,2014,274,133,144,42,45,1,11,20,21,19,1,1,2,0,3
40,Sala Francesco,2015,114,15,9,27,3,13,35,34,23,34,0,1,1,3,5
28,Raucci Salvatore,2015,184,275,142,109,31,7,12,10,13,26,1,1,1,0,2
57,Danesi Davide,2015,133,78,24,33,17,11,25,27,21,28,0,2,1,2,5
14,Ulliana Andrea,2017,269,122,9,1,3,1,12,29,37,36,0,1,0,3,4
18,Deniskin Nikita,2017,142,13,6,12,4,10,27,30,30,35,1,0,0,4,4
52,Vizzari Giacomo,2018,156,111,170,65,10,10,17,10,14,31,1,1,1,1,3
51,Straffelini Cesare,2018,265,151,70,8,26,3,15,19,30,25,1,0,2,1,3
47,Corso Gabriele,2018,253,198,33,16,34,4,13,24,21,24,1,0,2,1,3
10,Lattaruolo Gianmarco,2018,176,151,87,11,43,9,15,17,27,23,2,1,1,1,3
29,Pruneri Fabio,2018,134,41,5,7,7,11,25,34,31,32,0,1,1,3,5
23,Viola Federico,2018,176,17,1,2,2,9,28,37,39,39,1,0,0,4,4
30,Protopapa Matteo,2018,234,151,53,28,282,5,15,22,18,1,1,0,2,0,2
38,Pierro Lorenzo,2019,198,189,160,21,22,13,9,10,26,22,1,0,0,2,2
20,Marino Domenico,2019,176,132,23,43,31,14,14,20,23,20,1,1,2,1,4
7,Tarini Bernardo,2019,47,7,4,3,9,24,33,35,37,29,0,0,1,4,5
17,Marzenta Giovanni,2020,212,106,21,13,17,7,12,26,25,31,0,1,0,3,4
6,Morgante Matteo,2021,135,250,105,77,66,11,5,14,20,19,0,3,1,0,4
43,Bordigoni Fabio,2021,86,67,105,43,10,13,20,14,24,26,0,2,2,1,5
5,Baccioli Avio,2022,81,49,126,41,82,19,17,15,22,20,0,3,2,0,5
4,Tafuri Paolo,2022,263,60,91,13,27,3,16,18,25,26,0,1,2,1,4
27,Foschi Massimiliano,2022,13,1,1,1,1,30,39,42,42,42,0,0,0,5,5
39,Bartoli Davide,2022,263,241,230,13,12,3,3,6,25,29,0,0,0,2,2
8,Calogero Giacomo,2022,114,49,34,26,27,17,17,25,23,26,0,1,4,0,5
24,Stancanelli Valerio,2022,43,15,12,10,5,23,23,33,26,35,0,0,1,4,5
56,De Pietri Daniele,2023,83,60,7,34,12,15,22,28,25,32,0,1,2,2,5
33,Bertoli Michele,2023,241,84,57,103,159,3,19,20,18,12,0,2,1,0,3
34,Risari Leonardo,2023,293,101,151,167,126,0,17,13,13,14,1,2,0,0,2
53,Lugli Francesco,2023,241,205,151,62,36,3,8,13,22,25,1,0,2,0,2
49,Botticella Raffaele,2024,218,121,18,7,3,7,15,28,33,37,1,1,0,3,4
1,Balistri Edoardo,2024,205,121,12,4,4,8,15,29,36,36,0,1,0,3,4
55,Zonta Enrico,2024,245,66,7,2,1,4,19,32,38,42,0,0,1,3,4

In [19]:
df = df.reset_index(drop=True)

In [22]:
df = df.astype({"studente": str, "anno_finale": int,
              "pos1": int, "pos2": int, "pos3": int, "pos4": int, "pos5": int,
              "pt1": int, "pt2": int, "pt3": int, "pt4": int, "pt5": int,
              "menzione": int, "bronzo": int, "argento": int, "oro": int, "medaglie": int})
df.dtypes

studente       object
anno_finale     int32
pos1            int32
pos2            int32
pos3            int32
pos4            int32
pos5            int32
pt1             int32
pt2             int32
pt3             int32
pt4             int32
pt5             int32
menzione        int32
bronzo          int32
argento         int32
oro             int32
medaglie        int32
dtype: object

In [24]:
df[df["pos1"] <= 30]

,studente,anno_finale,pos1,pos2,pos3,pos4,pos5,pt1,pt2,pt3,pt4,pt5,menzione,bronzo,argento,oro,medaglie
15,Fogari Andrea,2010,9,2,1,3,28,28,39,37,39,16,0,0,1,4,5
47,Foschi Massimiliano,2022,13,1,1,1,1,30,39,42,42,42,0,0,0,5,5

In [25]:
df.to_pickle("data/da_usare/Cese_2003-2024_fives.pickle")